version: '3'

services:

#  base:
#    image: markussitzmann/appdock_base:${APPDOCK_BUILD_LABEL}
#    container_name: appdock_base
#    build:
#      context: base/
#    networks:
#      - rope
#    volumes:
#      - "${APPDOCK_HOME}:/home/appdock"
#    environment:
#      - APPDOCK_BUILD_LABEL
#      - APPDOCK_HOME
#      - APPDOCK_USER
#      - APPDOCK_UID
#      - APPDOCK_GID

  proxy:
    image: markussitzmann/appdock_proxy:${APPDOCK_BUILD_LABEL}
    container_name: appdock_proxy
    build:
      context: https://github.com/markussitzmann/nginx-proxy.git#appdock
      #args:
      #  build_label: ${APPDOCK_BUILD_LABEL}
    networks:
      - "rope"

#  hull:
#    image: markussitzmann/appdock_hull:${APPDOCK_BUILD_LABEL}
#    container_name: appdock_hull
#    build:
#      context: hull/
#    depends_on:
#      - "base"

  prototype:
    image: markussitzmann/appdock_prototype_conda_django:${APPDOCK_BUILD_LABEL}
    container_name: appdock_prototype2
    command: bash
    volumes:
      - "${APPDOCK_HOME}:/home/appdock"
    environment:
      - APPDOCK_BUILD_LABEL
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID

  shell:
    image: markussitzmann/appdock_shell:${APPDOCK_BUILD_LABEL}
    container_name: appdock_shell
    #depends_on:
    #  - "base"
    command: bash
    volumes:
      - "${APPDOCK_HOME}:/home/appdock"
    networks:
      - "rope"
    environment:
      - APPDOCK_BUILD_LABEL
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID

  db:
    image: markussitzmann/appdock_db:${APPDOCK_BUILD_LABEL}
    container_name: appdock_db
    build:
      context: https://github.com/markussitzmann/docker-postgresql.git#appdock
      #args:
      #  build_label: ${APPDOCK_BUILD_LABEL}
    volumes:
       - /srv/docker/appdockdb:/var/lib/postgresql
    #depends_on:
    #   - "base"
    networks:
       - "rope"
    environment:
      - DEBUG=false

      - APPDOCK_BUILD_LABEL
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID

      - DB_USER=${APPDOCK_USER}
      - DB_PASS=${APPDOCK_DB_PASSWORD}
      - DB_NAME=${APPDOCK_USER}
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

networks:
  rope:



