version: '3'

services:

  base:
     environment:
      - TUG_GID
      - TUG_UID
      - TUG_HOME
      - BUILD_LABEL
     build:
       context: base/
     image: markussitzmann/appdock_base:${BUILD_LABEL}
     networks:
      - rope
#     volumes:
#      - "${TUG_HOME}:/home/tug"
#
#  shell:
#    environment:
#      - TUG_GID
#      - TUG_UID
#      - TUG_HOME
#    build:
#       context: shell/
#    depends_on:
#      - "keel"
#    #command: bash
#    #stdin_open: true
#    #tty: true
#    volumes:
#      - "${TUG_HOME}:/home/tug"
#    image: markussitzmann/shell:1
#    networks:
#      - rope


  db:
    environment:
      - BUILD_LABEL
      - DEBUG=false

      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    build:
      context: https://github.com/markussitzmann/docker-postgresql.git#appdock
      args:
        build_label: ${BUILD_LABEL}
    image: markussitzmann/appdock_db:${BUILD_LABEL}
    volumes:
       - /srv/docker/appdockdb:/var/lib/postgresql
    depends_on:
       - "base"
    networks:
       - "rope"

networks:
  rope:



