version: '3'

services:

  base:
     environment:
      - APPDOCK_BUILD_LABEL
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID
     build:
       context: base/
     image: markussitzmann/appdock_base:${APPDOCK_BUILD_LABEL}
     networks:
      - rope
     volumes:
      - "${APPDOCK_HOME}:/home/appdock"

  shell:
    environment:
      - APPDOCK_BUILD_LABEL
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID
    build:
       context: shell/
    depends_on:
      - "base"
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - "${APPDOCK_HOME}:/home/appdock"
    image: markussitzmann/appdock_shell:${APPDOCK_BUILD_LABEL}
    networks:
      - "rope"


  db:
    environment:
      - DEBUG=false

      - APPDOCK_BUILD_LABEL
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID

      - DB_USER=${APPDOCK_USER}
      - DB_PASS=${APPDOCK_DB_PASSWORD}
      - DB_NAME=${APPDOCK_USER}
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    build:
      context: https://github.com/markussitzmann/docker-postgresql.git#appdock
      args:
        build_label: ${APPDOCK_BUILD_LABEL}
    image: markussitzmann/appdock_db:${APPDOCK_BUILD_LABEL}
    volumes:
       - /srv/docker/appdockdb:/var/lib/postgresql
    depends_on:
       - "base"
    networks:
       - "rope"

networks:
  rope:



