#!/bin/bash

source .env

mkdir -p $APPDOCK_HOME && mkdir -p $APP_HOME

docker-compose -f ./context/docker-compose.yml run --rm base
docker-compose -f ./context/django/docker-compose.init.yml run  --rm django


