version: '3'

services:

  proxy:
    image: markussitzmann/appdock_proxy:${APPDOCK_BUILD_LABEL}
    container_name: appdock_proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${APPDOCK_HOME}:/home/appdock"
    ports:
      - "80:80"
    networks:
      - rope

  shell:
    image: markussitzmann/appdock_shell:${APPDOCK_BUILD_LABEL}
    container_name: appdock_shell
    command: bash
    volumes:
      - "${APPDOCK_HOME}:/home/appdock"
    networks:
      - rope
    environment:
      - APPDOCK_BUILD_LABEL
      - APPDOCK_ROOT
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID

  db:
    image: markussitzmann/appdock_db:${APPDOCK_BUILD_LABEL}
    container_name: appdock_db
    volumes:
       #- /srv/docker/appdockdb:/var/lib/postgresql
      - db_volume:/var/lib/postgresql
    networks:
      - rope
    environment:
      - DEBUG=true
      - APPDOCK_BUILD_LABEL
      - APPDOCK_ROOT
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID
      - DB_USER=${APPDOCK_USER}
      - DB_PASS=${APPDOCK_DB_PASSWORD}
      - DB_NAME=${APPDOCK_USER}
      - DB_TEMPLATE=
      - DB_EXTENSION=rdkit
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

volumes:
  db_volume:

networks:
  rope:



