#!/bin/bash

source ../.env

docker push markussitzmann/appdock_shell:$APPDOCK_BUILD_LABEL
docker push markussitzmann/appdock_db:$APPDOCK_BUILD_LABEL
docker push markussitzmann/appdock_django:$APPDOCK_BUILD_LABEL
docker push markussitzmann/appdock_app:$APPDOCK_BUILD_LABEL

