#!/bin/bash

echo "Running $@"

docker-compose exec app bash -ci "gosu appdock bash -c 'cd /home/app/ && manage.py $*'"


#docker-compose run --rm app bash -ci "\
#	cd /home/apps/ &&\
#	./manage.py $*"