version: '3'

services:

  django:
    image: markussitzmann/appdock_django:${APPDOCK_BUILD_LABEL}
    container_name: django
    volumes:
      - "${APPDOCK_HOME}:/home/appdock"
      - "${APP_HOME}:/home/app"
    environment:
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID
      - APP_HOME
    networks:
      - rope

networks:
  rope:
