version: '3'

services:

  app:
    image: markussitzmann/appdock_app:${APPDOCK_BUILD_LABEL}
    container_name: app
    volumes:
      - "${APPDOCK_HOME}:/home/appdock"
      - "${APP_HOME}:/home/app"
    ports:
       - "8000:80"
    networks:
      - rope
    environment:
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID
      - APP_HOME
      - VIRTUAL_HOST=whoami.local

  proxy:
    image: markussitzmann/appdock_proxy:${APPDOCK_BUILD_LABEL}
    container_name: appdock_proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${APPDOCK_HOME}:/home/appdock"
    ports:
      - "80:80"
    networks:
      - rope

  db:
    image: markussitzmann/appdock_db:${APPDOCK_BUILD_LABEL}
    container_name: appdock_db
    volumes:
       - /srv/docker/appdockdb:/var/lib/postgresql
    environment:
      - DEBUG=false

      - APPDOCK_BUILD_LABEL
      - APPDOCK_ROOT
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID

      - DB_USER=${APPDOCK_USER}
      - DB_PASS=${APPDOCK_DB_PASSWORD}
      - DB_NAME=${APPDOCK_USER}
      - DB_TEMPLATE=

      - DB_EXTENSION=rdkit

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    networks:
      - rope

networks:
  rope:



