version: '3'

services:

  base:
    image: markussitzmann/appdock_base:${APPDOCK_BUILD_LABEL}
    build:
      context: base/
    volumes:
      - "${APPDOCK_HOME}:/home/appdock"
    environment:
      - APPDOCK_BUILD_LABEL
      - APPDOCK_HOME
      - APPDOCK_USER
      - APPDOCK_UID
      - APPDOCK_GID

  proxy:
    image: markussitzmann/appdock_proxy:${APPDOCK_BUILD_LABEL}
    build:
      context: https://github.com/markussitzmann/nginx-proxy.git#appdock

  python:
    image: markussitzmann/appdock_python:${APPDOCK_BUILD_LABEL}
    build:
      context: python/
      args:
        build_label: ${APPDOCK_BUILD_LABEL}
    depends_on:
      - base

  rdkit:
    image: markussitzmann/appdock_rdkit:${APPDOCK_BUILD_LABEL}
    build:
      context: rdkit/
      args:
        build_label: ${APPDOCK_BUILD_LABEL}
    depends_on:
      - python

  django:
    image: markussitzmann/appdock_django:${APPDOCK_BUILD_LABEL}
    build:
      context: django/
      args:
        build_label: ${APPDOCK_BUILD_LABEL}
    depends_on:
      - rdkit

  shell:
    image: markussitzmann/appdock_shell:${APPDOCK_BUILD_LABEL}
    build:
      context: shell/
      args:
        build_label: ${APPDOCK_BUILD_LABEL}
    depends_on:
      - python
    command: bash

  db:
    image: markussitzmann/appdock_db:${APPDOCK_BUILD_LABEL}
    build:
      context: https://github.com/markussitzmann/docker-postgresql.git#appdock
      args:
        build_label: ${APPDOCK_BUILD_LABEL}
    depends_on:
       - base

  app:
    image: markussitzmann/appdock_app:${APPDOCK_BUILD_LABEL}
    build:
      context: app/
      args:
        build_label: ${APPDOCK_BUILD_LABEL}
    depends_on:
      - django




